### ISSUE TITLE
how can i use wired-elements?

### ISSUE THREAD

**Issue by djary** [wiredjs/wired-elements#116]
how can I use it? `<script src="https://unpkg.com/wired-elements@latest/dist/wired-elements.bundled.js"></script>` give 404 error ? and in package are typescripts files

**Comment by sumgup** [comment]
I am facing the same issue, looks like something wrong with CDN.  Although I can access the file on CDN server when I type the URL.

**Comment by olivermicke** [comment]
In the source of https://wiredjs.com/ I was able to find a bundled JS file. I assume it's version 2.0.0. Check it out here:

https://wiredjs.com/dist/main.min.js

**Comment by sumgup** [comment]
This helps

**Comment by olivermicke** [comment]
I found another bundle in the [component showcase section](https://wiredjs.com/showcase.html). I tried it out with the `wired-progress` component and it seems to work.

If you want to quickly check whether a component works, I have created a JSFiddle:
https://jsfiddle.net/o4vfa2x0/

Here is the link to the showcase bundle:
https://wiredjs.com/dist/showcase.min.js

**Comment by Mashiane** [comment]
Ta, this should do!

**Comment by butu5** [comment]
https://wiredjs.com/dist/showcase.min.js worked however through webpack it's not recognising many elements.

**Comment by pshihn** [comment]
Sorry for not responding sooner. I had removed the bundled version of the project because everyone was using it. The bundled version is now shipped with v2.0.3
You can load it on your page from https://unpkg.com/wired-elements@2.0.3/lib/wired-elements-bundled.js

See a live example on glitch: https://glitch.com/~wired-elements-vanilla

Note: Please do not use shocase.min.

**Comment by pshihn** [comment]
Sorry https://unpkg.com/wired-elements@2.0.5/lib/wired-elements-bundled.js is the latest
