### ISSUE TITLE
Production Build Error

### ISSUE THREAD

**Issue by rajanmagar** [wiredjs/wired-elements#14]
Failed to modify the code from this file

./node_modules/@polymer/lit-element/lit-elelment.js:12

**Comment by pshihn** [comment]
Sorry don't know what build you're running and why it's trying to modify that file.

**Comment by shenzekun** [comment]
same problem! I use create-react-app create a program and use `wired-elements`,but when I run `yarn bulid`,appear this
![image](https://user-images.githubusercontent.com/21151080/40652887-271aa30c-636c-11e8-936c-20255aa7b418.png)

**Comment by pshihn** [comment]
This is likely because the target of the build is set to ES5. There may be other solutions out there. Don't think it is specific to wired-elements. But anyone using [lit-element](https://github.com/Polymer/lit-element)

https://github.com/facebook/create-react-app/blob/master/packages/react-scripts/template/README.md#npm-run-build-fails-to-minify

**Comment by bencoullie** [comment]
Same problem here 👍

**Comment by sashahavia** [comment]
Same here. Did anyone find the solution?

**Comment by pshihn** [comment]
The easiest work around is the use the bundled version in your app
```html
<script src="https://unpkg.com/wired-elements@0.8.0/dist/wired-elements.bundled.min.js"></script>
```

**Comment by pshihn** [comment]
This demo CodeSandbox shows usage of wired-elements in create-react-app. 
https://codesandbox.io/embed/xrll5wyl8w
(uses the latest wired-elements build)
